package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Book;
import lt.vu.mybatis.model.User;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BookMapper {


    List <User> selectHistoryForBook(String isbn);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    int deleteByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    Book selectByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    int updateByPrimaryKey(Book record);
}