package lt.vu.mybatis.dao;

import java.util.List;

import lt.vu.mybatis.model.Book;
import lt.vu.mybatis.model.User;
import org.mybatis.cdi.Mapper;

@Mapper
public interface UserMapper {
    List <Book> selectHistoryForUser(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USER
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    int deleteByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USER
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USER
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    User selectByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USER
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USER
     *
     * @mbg.generated Sun Mar 19 20:38:34 EET 2023
     */
    int updateByPrimaryKey(User record);
}